### ISSUE TITLE
ValueError: signal number 32 out of range

### ISSUE THREAD

**Issue by tokaka22** [yaoyao-liu/class-incremental-learning#33]
**It's pip list followed by README.md**
Package       Version
------------- ---------------
certifi       2016.2.28
cffi          1.10.0
joblib        1.1.0
mkl-fft       1.3.0
mkl-random    1.1.1
mkl-service   2.3.0
numpy         1.19.2
olefile       0.44
Pillow        6.2.2
pip           21.3.1
protobuf      3.19.1
pycparser     2.18
scikit-learn  0.24.2
scipy         1.5.4
setuptools    36.4.0
six           1.10.0
sklearn       0.0
tensorboardX  2.4.1
threadpoolctl 3.0.0
torch         1.2.0
torchvision   0.4.0a0+6b959ee
tqdm          4.62.3
wheel         0.29.0
**following error：**
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/tokaka22/.conda/envs/AANets-PyTorch/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/tokaka22/.conda/envs/AANets-PyTorch/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tokaka22/.conda/envs/AANets-PyTorch/lib/python3.6/multiprocessing/resource_sharer.py", line 139, in _serve
    signal.pthread_sigmask(signal.SIG_BLOCK, range(1, signal.NSIG))
  File "/home/tokaka22/.conda/envs/AANets-PyTorch/lib/python3.6/signal.py", line 60, in pthread_sigmask
    sigs_set = _signal.pthread_sigmask(how, mask)
ValueError: signal number 32 out of range

 I must set num_workers to 0 which may cost too much time. Another solution is upgrade to Python 3.7 (but in README.md it said "conda create --name AANets-PyTorch python=3.6")
How can i fix it?

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

According to your log, it seems the error didn't happen in my code. It is a bug of python.
Maybe you need to upgrade your python version to solve the problem ([see the discussion on slackoverflow](https://stackoverflow.com/questions/53300965/pytorch-exception-in-thread-valueerror-signal-number-32-out-of-range?rq=1)).

My python version is 3.6.10. If python 3.7 works for you, I think it is okay to use python 3.7 to run this project.
